name: flutter_audio_desktop_fermat
description: An audio playback library for Flutter Desktop. Supports Windows & Linux. Based on miniaudio.
version: 0.1.2
homepage: https://github.com/fermat28/flutter_audio_desktop
repository: https://github.com/fermat28/flutter_audio_desktop
documentation: https://github.com/fermat28/flutter_audio_desktop/blob/master/README.md

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  path_provider: ^2.0.9
  plugin_platform_interface: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FlutterAudioDesktopPlugin
      windows:
        pluginClass: FlutterAudioDesktopPlugin
